CREATE TABLE QUESTION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    question_text VARCHAR(255) NOT NULL,
    correct_answer VARCHAR(255) NOT NULL
);

CREATE TABLE QUESTION_OPTIONS (
    question_id BIGINT NOT NULL,
    options VARCHAR(255) NOT NULL,
    FOREIGN KEY (question_id) REFERENCES QUESTION(id)
);
